import type { Prisma, Proposal } from "@prisma/client";
import { promises as fs } from "fs";
import path from "path";
import { parseGeneratedFiles } from "@/server/contracts/generated-file.contract";
import { assertCanGenerateFiles } from "@/server/invariants/proposal-invariants";
import { extractFeatureSlug } from "@/lib/utils";

type TxClient = Prisma.TransactionClient;

export class MarkdownGenerator {
  async generate(tx: TxClient, proposal: Proposal) {
    assertCanGenerateFiles(proposal.status);

    const slug = extractFeatureSlug(proposal.title);
    const generatedDir = path.join(process.cwd(), "generated");

    const files = parseGeneratedFiles([
      { path: `docs/features/${slug}.md`, content: this.featureDoc(proposal) },
      { path: `docs/architecture/${slug}.md`, content: this.architectureDoc(proposal) },
      { path: `docs/api/${slug}.md`, content: this.apiDoc(proposal, slug) },
      { path: `tasks/${slug}.cursor.md`, content: this.taskDoc(proposal) },
    ]);

    for (const file of files) {
      await tx.generatedFile.create({
        data: {
          proposalId: proposal.id,
          path: file.path,
          content: file.content,
          mimeType: file.mimeType,
        },
      });

      const fullPath = path.join(generatedDir, file.path);
      await fs.mkdir(path.dirname(fullPath), { recursive: true });
      await fs.writeFile(fullPath, file.content, "utf-8");
    }
  }

  private featureDoc(proposal: Proposal): string {
    return `# Feature: ${proposal.title}

## Summary
${proposal.summary}

## Chosen Solution
${proposal.chosenSolution}

## Alternatives Considered
${proposal.alternativesConsidered.map((a) => `- ${a}`).join("\n")}

## Reasoning
${proposal.reasoning.map((r) => `- ${r}`).join("\n")}

## Risks
${proposal.risks.map((r) => `- ${r}`).join("\n")}

## Vote Classification
${proposal.voteClassification ?? "unknown"}

---
*Generated by OceanTechAI Workspace after Founder approval.*
`;
  }

  private architectureDoc(proposal: Proposal): string {
    return `# Architecture: ${proposal.title}

## Overview
Technical architecture for: ${proposal.title}

## Chosen Solution
${proposal.chosenSolution}

## Design Decisions
${proposal.reasoning.map((r) => `- ${r}`).join("\n")}

## Risks & Mitigations
${proposal.risks.map((r) => `- ${r}`).join("\n")}

## Data Model (Draft)
- Core entities derived from feature requirements
- PostgreSQL with Prisma ORM
- Indexed foreign keys on lookup fields

---
*Generated by OceanTechAI Workspace after Founder approval.*
`;
  }

  private apiDoc(proposal: Proposal, slug: string): string {
    return `# API: ${proposal.title}

## Base Path
\`/api/v1/${slug}\`

## Endpoints (Draft)

### POST /api/v1/${slug}
Create resource.

### GET /api/v1/${slug}/:id
Get resource by ID.

### PATCH /api/v1/${slug}/:id
Update resource.

## Notes
${proposal.chosenSolution}

---
*Generated by OceanTechAI Workspace after Founder approval.*
`;
  }

  private taskDoc(proposal: Proposal): string {
    return `# Task: ${proposal.title}

## Context
${proposal.summary}

## Implementation Tasks
${proposal.tasksToCreate.map((t) => `- [ ] ${t}`).join("\n")}

## Files to Create
${proposal.filesToCreate.map((f) => `- [ ] ${f}`).join("\n")}

## Acceptance Criteria
- [ ] Core feature implemented per chosen solution
- [ ] P0 test cases pass
- [ ] Red Team mitigations addressed
- [ ] API endpoints functional

---
*Generated by OceanTechAI Workspace — ready for Cursor agent execution.*
`;
  }
}

export const markdownGenerator = new MarkdownGenerator();
