export const JOURNAL_TYPES = {
  LESSON_LEARNED: "LESSON_LEARNED",
  OBSERVATION: "OBSERVATION",
  DECISION: "DECISION",
  DISCUSSION_SUMMARY: "DISCUSSION_SUMMARY",
  WARNING: "WARNING",
  IDEA: "IDEA",
  RETROSPECTIVE: "RETROSPECTIVE",
} as const;

export type JournalType = (typeof JOURNAL_TYPES)[keyof typeof JOURNAL_TYPES];
